@startuml
class Commit_c9bb7bf {
C:\\Users\\Lenovo\\PycharmProjects\\dz2\\Project.py
}
Commit_f1565ff --> Commit_c9bb7bf
class Commit_f1565ff {
C:\\Users\\Lenovo\\PycharmProjects\\dz2\\dependency_graph.puml
}
Commit_b1b87bf --> Commit_f1565ff
class Commit_b1b87bf {
C:\\Users\\Lenovo\\PycharmProjects\\dz2\\dependency_graph.png
}
Commit_b79be4e --> Commit_b1b87bf
class Commit_b79be4e {
C:\\Users\\Lenovo\\PycharmProjects\\dz2\\.idea\\dz2.iml
}
Commit_ce2ff5b --> Commit_b79be4e
class Commit_ce2ff5b {
C:\\Users\\Lenovo\\PycharmProjects\\dz2\\Project.py
}
Commit_9f1e79f --> Commit_ce2ff5b
class Commit_9f1e79f {
C:\\Users\\Lenovo\\PycharmProjects\\dz2\\Project.py
}
Commit_425ae10 --> Commit_9f1e79f
class Commit_425ae10 {

}
@enduml